GET  http://localhost:3001/api/apuestas 
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxZjNlOTdmMmE0ZjQ0Njc5NjFkODI3YyIsInVzZXJuYW1lIjoiT3RybyB1c3VhcmlvIiwiaWF0IjoxNjQ1MTE4OTk2LCJleHAiOjE2NDU3MjM3OTZ9.9Bt1xkBto9jZ0G73-zc_CHTO-7lPvvRTozKauiOSBgQ
