POST  http://localhost:3001/api/users 
Content-Type: application/json

{
  "username": "Usuario desde Vcode requests 1",
  "name": "Eric",
  "password": "contraseña_eric",
  "apuestas": []
}
 
###

POST  http://localhost:3001/api/users
Content-Type: application/json

{
}
