POST  http://localhost:3001/api/users 
Content-Type: application/json

{
  "username": "holfae",
  "name": "Eric",
  "email": "eric.lorien92@gmail.com",
  "password": "Contrasena-eric3",
  "apuestas": []
}
 
###

POST  http://localhost:3001/api/users
Content-Type: application/json

{
}
